# This is the default configuration file. This could be named docker-compose.dev.yml or similar, however the lack of a docker-compose.yml
# would confuse Compose if there's a docker-compose.yml anywhere in any parent directory of the project checkout path (it would run that,
# and switch the compose project directory completely to that).
#
# Thus, this is designed to be the main config file, and everything else to be added to this as overlays in your .env file.
services:
  pg:
    extends:
      service: pg
      file: docker-compose.common.yml
    env_file:
      - .env
    ports:
      - 5432:5432
    environment:
      PGDATA: /root/pg
    volumes:
      - .:/app
      - ./.home:/root

  mc:
    extends:
      service: mc
      file: docker-compose.common.yml

  redis:
    extends:
      service: redis
      file: docker-compose.common.yml

  worker:
    extends:
      service: worker
      file: docker-compose.common.yml
    depends_on:
      - pg
      - redis

  web:
    extends:
      service: python
      file: docker-compose.common.yml
    env_file:
      - .env
    environment:
      DJANGO_DB_MIGRATE: x
    ports:
      - "8000:8000"
    depends_on:
      - pg
      - mc
      - redis
    command: [
      "pysu", "app",
      "django-admin",
      "runserver",
      "--insecure",
      "0.0.0.0:8000"
    ]
    stop_signal: SIGINT
