# This file contains mostly build definitions. Ports, env files and dependencies have no place because this file would be used for release
# or test configurations.
# Volumes shouldn't either, but we're making a compromise for DRY-ness.
services:
  mc:
    image: memcached:1@sha256:3e4cfa8274fc07f27f040ec994c7506a4438a835e2e229673b3da06c8c3d99b2

  redis:
    image: redis:7@sha256:4421962706d7a901cbd435282515704040203d67c653160e3a46a27b79c40e19

  pg:
    build:
      context: docker/postgres
    shm_size: 4g
    command: [
      'postgres',
      '-c', 'log_lock_waits=true',
      '-c', 'log_min_error_statement=WARNING',
      '-c', 'log_min_duration_statement=1s',

      # debug
#      '-c', 'log_statement=all',
#      '-c', 'log_duration=true',
#      '-c', 'log_disconnections=true',
#      '-c', 'log_connections=true',

      # tuning
      '-c', 'max_wal_size=10GB',
      '-c', 'work_mem=4GB',
      '-c', 'checkpoint_timeout=1h',
      '-c', 'shared_buffers=1GB',
      '-c', 'autovacuum=false',
      '-c', 'maintenance_work_mem=1GB',

      # danger
#      '-c', 'full_page_writes=off',
#      '-c', 'wal_level=minimal',
#      '-c', 'max_wal_senders=0',
#      '-c', 'fsync=off',
#      '-c', 'synchronous_commit=off',
    ]

  pgupgrade:
    image: pgautoupgrade/pgautoupgrade:17-bookworm@sha256:6ce11cbff9ceb6cfa591bc642bbb1cf6dde41c136fde336a57e561a34051d8f5
    environment:
      POSTGRES_PASSWORD: app
      PGAUTO_ONESHOT: yes

  python:
    build:
      context: docker/python
      additional_contexts:
        requirements-context: requirements
        src-context: src
      args:
        DJANGO_COLLECTSTATIC:
        DJANGO_SETTINGS_MODULE:
        REQUIREMENTS: base
        SERVER_NAME:
    environment:
      PYTHONHUNTER:
      PYTHONHUNTERCONFIG:
      DJANGO_DEBUG:
      DJANGO_DEBUG_SQL:
      DJANGO_DEBUG_SQL_LIMIT:
      DJANGO_DEBUG_TOOLBAR:
      LOGGING_LEVEL:
      LOGGING_PATH:
    deploy:
      resources:
        limits:
          memory: ${MEMORY_LIMIT:-4G}
    cap_add:
      - SYS_PTRACE
    ulimits:
      nproc: 16384
      nofile:
        soft: 65536
        hard: 262144
    volumes:
      - .:/app
      - ./.home:/root
      - ./.home:/home/app
      - ./.home:/var/app
    init: true

  worker:
    extends:
      service: python
    deploy:
      replicas: 2
    command: [
      'pysu', 'app', '--',
      'django-admin', 'rqworker'
    ]

  reloader:
    build:
      context: docker/reloader
    environment:
      RELOADER_MONITOR:
      RELOADER_CONTAINERS:
      COMPOSE_PROJECT_NAME:
    volumes:
      - .:/app
      - /var/run/docker.sock:/var/run/docker.sock
      - ./.home/run:/var/app/run
    ulimits:
      nproc: 16384
      nofile:
        soft: 65536
        hard: 262144
