version: '3.8'

x-python:
  &python
  build:
    context: .
    dockerfile: docker/python/Dockerfile
    args:
      REQUIREMENTS: base
      DJANGO_SETTINGS_MODULE:
      DJANGO_COLLECTSTATIC: x
  environment:
    PYTHONHUNTER:
    PYTHONHUNTERCONFIG:
    DJANGO_DEBUG:
    DJANGO_DEBUG_SQL:
    DJANGO_DEBUG_SQL_LIMIT:
    DJANGO_DEBUG_TOOLBAR:
    LOGGING_LEVEL:
    LOGGING_PATH:
  env_file:
    - .env
  tty: false
  volumes:
    - .:/app
    - ./.home:/root
    - ./.home:/home/app
    - ./.home:/var/app
    - ./.home/etc:/etc/app
services:
  pg:
    build:
      context: docker/postgres
    environment:
      POSTGRES_USER:
      POSTGRES_PASSWORD:
      POSTGRES_DB:
      PGDATA:
    command: [
      'postgres',
      '-c', 'log_lock_waits=true',
      '-c', 'log_min_error_statement=WARNING',
      '-c', 'log_min_duration_statement=1s',
    ]
    volumes:
      - .:/app
      - ./.home:/root

  mc:
    image: memcached:1@sha256:3b793890596173d412c8b4ab70f5206a2143e74222ded6a61768edca87b6d529

  redis:
    image: redis:7@sha256:f50031a49f41e493087fb95f96fdb3523bb25dcf6a3f0b07c588ad3cdbe1d0aa

  cron:
    <<: *python
    depends_on:
      - pg
    entrypoint: [ '/entrypoint.sh' ]
    command: [ 'pysu', 'app', '--', 'yacron', '--config=/etc/app/yacron.yml' ]

  web:
    <<: *python
    depends_on:
      - pg
      - mc
      - redis
    entrypoint: [ '/entrypoint.sh' ]

  worker:
    <<: *python
    entrypoint: [ '/entrypoint.sh' ]
    command: [
      'pysu', 'app', '--',
      'django-admin', 'rqworker'
    ]
    depends_on:
      - pg
      - redis
    deploy:
      replicas: 2
