services:
  reloader:
    extends:
      service: reloader
      file: docker-compose.common.yml

  web:
    # Because this file is an overlay this service is not completely defined.
    environment:
      DJANGO_COLLECTSTATIC: x
    volumes:
      - ./.home/run:/var/app/run
      - ./.home/static:/var/app/static
    stop_signal: SIGTERM
    command: [
      'uwsgi',
      '--ini', '/etc/app/uwsgi.ini',
      '--processes', '4',
    ]

  nginx:
    extends:
      service: python
      file: docker-compose.common.yml
    build:
      args:
        REQUIREMENTS: nginx
    volumes:
      - ./.home/etc:/shared/${SERVER_NAME}/etc
      - ./.home/run:/shared/${SERVER_NAME}/run
      - ./.home/static:/shared/${SERVER_NAME}/static
      - ./.home/etc:/etc/app
    depends_on:
      - web
    ports:
      - '80:80'
      - '443:443'
    command: [
      'holdup',
      '--verbose', 'unix:///shared/${SERVER_NAME}/run/uwsgi.sock',
      '--',
      'nginx',
    ]
