version: '3.7'

services:
  nginx:
    image: ${registry_host}/${compose_project_name}-nginx:${app_version}
    build:
      context: ../..
      dockerfile: docker/python/Dockerfile
      args:
        REQUIREMENTS: nginx
        USER_ID: 2000
        GROUP_ID: 2000
  demo:
    image: ${registry_host}/${compose_project_name}-demo:${app_version}
    build:
      context: ../..
      dockerfile: docker/python/Dockerfile
      args:
        REQUIREMENTS: base
        DJANGO_SETTINGS_MODULE: ${django_settings_module}
        USER_ID: 2001
        GROUP_ID: 2001
        SERVER_NAME: demo.example.com
  worker:
    image: ${registry_host}/${compose_project_name}-worker:${app_version}
    build:
      context: ../..
      dockerfile: docker/python/Dockerfile
      args:
        REQUIREMENTS: base
        DJANGO_SETTINGS_MODULE: ${django_settings_module}
        USER_ID: 2002
        GROUP_ID: 2002
  cron:
    image: ${registry_host}/${compose_project_name}-cron:${app_version}
    build:
      context: ../..
      dockerfile: docker/python/Dockerfile
      args:
        REQUIREMENTS: base
        DJANGO_SETTINGS_MODULE: ${django_settings_module}
        USER_ID: 2003
        GROUP_ID: 2003
  pg:
    image: ${registry_host}/${compose_project_name}-pg:${app_version}
    build:
      context: ../../docker/postgres
