
x-python:
  &python
  image: {{ registry_host }}/{{ service_name }}-python:{{ app_version }}
  env_file:
    - /services/{{ service_name }}/.env
  restart: unless-stopped
  volumes:
    - /services/{{ service_name }}/etc:/etc/app
    - /services/{{ service_name }}/logs:/var/app/logs
    - /services/{{ service_name }}/media:/var/app/media
    - /services/{{ service_name }}/run:/var/app/run
    - /services/{{ service_name }}/static:/var/app/static
  ulimits:
    nproc: 16384
    nofile:
      soft: 65536
      hard: 262144
  depends_on:
    - pg
    - mc
    - redis

services:
  nginx:
    image: {{ registry_host }}/{{ service_name }}-nginx:{{ app_version }}
    restart: always
    ports: ['80:80', '443:443']
    volumes:
      - /services/nginx/etc:/etc/letsencrypt
      - /services/nginx/logs:/var/log/letsencrypt
      - /services/nginx/logs:/var/app/logs
      - /services/{{ service_name }}/etc:/shared/{{ server_name }}/etc
      - /services/{{ service_name }}/logs:/shared/{{ server_name }}/logs
      - /services/{{ service_name }}/media:/shared/{{ server_name }}/media
      - /services/{{ service_name }}/run:/shared/{{ server_name }}/run
      - /services/{{ service_name }}/static:/shared/{{ server_name }}/static
      - /services/{{ service_name }}/.well-known:/shared/{{ server_name }}/.well-known
    ulimits:
      nproc: 16384
      nofile:
        soft: 65536
        hard: 262144
    command: [ 'nginx' ]
  {{ service_name }}:
    <<: *python
    command: [ 'uwsgi', '--ini', '/etc/app/uwsgi.ini' ]
  {{ service_name }}_worker:
    <<: *python
    command: [ 'pysu', 'app', '--', 'django-admin', 'rqworker' ]
    deploy:
      replicas: 2
  {{ service_name }}_cron:
    <<: *python
    command: [ 'pysu', 'app', '--', 'yacron', '--config=/etc/app/yacron.yml' ]
  pg:
    image: {{ registry_host }}/{{ service_name }}-pg:{{ app_version }}
    restart: unless-stopped
    command: [
      'postgres',
      '-c', 'log_lock_waits=true',
      '-c', 'log_min_error_statement=WARNING',
      '-c', 'log_min_duration_statement=1s',
      '-c', 'log_destination=stderr',
      '-c', 'logging_collector=on',
      '-c', 'log_directory=/var/log/postgresql',
      '-c', 'log_filename=pg-%Y-%m-%d.log',
      '-c', 'log_truncate_on_rotation=off',
      '-c', 'log_rotation_age=1d',
      '-c', 'log_rotation_size=0',
    ]
    shm_size: 256MB
    volumes:
      - /services/pg/data:/var/lib/postgresql
      - /services/pg/logs:/var/log/postgresql
    environment:
      PGUSER: app
      POSTGRES_USER: app
      POSTGRES_PASSWORD: app
      POSTGRES_EXTRAS:
  mc:
    image: memcached:1
    restart: always
  redis:
    image: redis:8
    restart: always
